// AUTO-GENERATED BY mkpkgs.go

package main

var stdpkgs = map[string][]pkg{
	"cc": []pkg{
		pkg{path: "cmd/cc", dir: "/go/src/cmd/cc"},
	},
	"yacc": []pkg{
		pkg{path: "cmd/yacc", dir: "/go/src/cmd/yacc"},
	},
	"libbio": []pkg{
		pkg{path: "libbio", dir: "/go/src/libbio"},
	},
	"textproto": []pkg{
		pkg{path: "net/textproto", dir: "/go/src/net/textproto"},
	},
	"signal": []pkg{
		pkg{path: "os/signal", dir: "/go/src/os/signal"},
	},
	"csv": []pkg{
		pkg{path: "encoding/csv", dir: "/go/src/encoding/csv"},
	},
	"syscall": []pkg{
		pkg{path: "internal/syscall", dir: "/go/src/internal/syscall"},
		pkg{path: "syscall", dir: "/go/src/syscall"},
	},
	"race": []pkg{
		pkg{path: "runtime/race", dir: "/go/src/runtime/race"},
	},
	"unsafe": []pkg{
		pkg{path: "unsafe", dir: "/go/src/unsafe"},
	},
	"parse": []pkg{
		pkg{path: "text/template/parse", dir: "/go/src/text/template/parse"},
	},
	"cmd": []pkg{
		pkg{path: "cmd", dir: "/go/src/cmd"},
	},
	"goobj": []pkg{
		pkg{path: "cmd/internal/goobj", dir: "/go/src/cmd/internal/goobj"},
	},
	"plugin": []pkg{
		pkg{path: "cmd/pprof/internal/plugin", dir: "/go/src/cmd/pprof/internal/plugin"},
	},
	"index": []pkg{
		pkg{path: "index", dir: "/go/src/index"},
	},
	"cmplx": []pkg{
		pkg{path: "math/cmplx", dir: "/go/src/math/cmplx"},
	},
	"mime": []pkg{
		pkg{path: "mime", dir: "/go/src/mime"},
	},
	"jsonrpc": []pkg{
		pkg{path: "net/rpc/jsonrpc", dir: "/go/src/net/rpc/jsonrpc"},
	},
	"armasm": []pkg{
		pkg{path: "cmd/internal/rsc.io/arm/armasm", dir: "/go/src/cmd/internal/rsc.io/arm/armasm"},
	},
	"report": []pkg{
		pkg{path: "cmd/pprof/internal/report", dir: "/go/src/cmd/pprof/internal/report"},
	},
	"heap": []pkg{
		pkg{path: "container/heap", dir: "/go/src/container/heap"},
	},
	"sort": []pkg{
		pkg{path: "sort", dir: "/go/src/sort"},
	},
	"nm": []pkg{
		pkg{path: "cmd/nm", dir: "/go/src/cmd/nm"},
	},
	"objdump": []pkg{
		pkg{path: "cmd/objdump", dir: "/go/src/cmd/objdump"},
	},
	"pprof": []pkg{
		pkg{path: "cmd/pprof", dir: "/go/src/cmd/pprof"},
		pkg{path: "net/http/pprof", dir: "/go/src/net/http/pprof"},
		pkg{path: "runtime/pprof", dir: "/go/src/runtime/pprof"},
	},
	"hmac": []pkg{
		pkg{path: "crypto/hmac", dir: "/go/src/crypto/hmac"},
	},
	"gosym": []pkg{
		pkg{path: "debug/gosym", dir: "/go/src/debug/gosym"},
	},
	"macho": []pkg{
		pkg{path: "debug/macho", dir: "/go/src/debug/macho"},
	},
	"gif": []pkg{
		pkg{path: "image/gif", dir: "/go/src/image/gif"},
	},
	"zip": []pkg{
		pkg{path: "archive/zip", dir: "/go/src/archive/zip"},
	},
	"x509": []pkg{
		pkg{path: "crypto/x509", dir: "/go/src/crypto/x509"},
	},
	"xml": []pkg{
		pkg{path: "encoding/xml", dir: "/go/src/encoding/xml"},
	},
	"color": []pkg{
		pkg{path: "image/color", dir: "/go/src/image/color"},
	},
	"symbolz": []pkg{
		pkg{path: "cmd/pprof/internal/symbolz", dir: "/go/src/cmd/pprof/internal/symbolz"},
	},
	"scanner": []pkg{
		pkg{path: "go/scanner", dir: "/go/src/go/scanner"},
		pkg{path: "text/scanner", dir: "/go/src/text/scanner"},
	},
	"hash": []pkg{
		pkg{path: "hash", dir: "/go/src/hash"},
	},
	"filepath": []pkg{
		pkg{path: "path/filepath", dir: "/go/src/path/filepath"},
	},
	"sql": []pkg{
		pkg{path: "database/sql", dir: "/go/src/database/sql"},
	},
	"bytes": []pkg{
		pkg{path: "bytes", dir: "/go/src/bytes"},
	},
	"api": []pkg{
		pkg{path: "cmd/api", dir: "/go/src/cmd/api"},
	},
	"fix": []pkg{
		pkg{path: "cmd/fix", dir: "/go/src/cmd/fix"},
	},
	"rsc.io": []pkg{
		pkg{path: "cmd/internal/rsc.io", dir: "/go/src/cmd/internal/rsc.io"},
	},
	"x86asm": []pkg{
		pkg{path: "cmd/internal/rsc.io/x86/x86asm", dir: "/go/src/cmd/internal/rsc.io/x86/x86asm"},
	},
	"svg": []pkg{
		pkg{path: "cmd/pprof/internal/svg", dir: "/go/src/cmd/pprof/internal/svg"},
	},
	"dsa": []pkg{
		pkg{path: "crypto/dsa", dir: "/go/src/crypto/dsa"},
	},
	"parser": []pkg{
		pkg{path: "go/parser", dir: "/go/src/go/parser"},
	},
	"io": []pkg{
		pkg{path: "io", dir: "/go/src/io"},
	},
	"mail": []pkg{
		pkg{path: "net/mail", dir: "/go/src/net/mail"},
	},
	"sync": []pkg{
		pkg{path: "sync", dir: "/go/src/sync"},
	},
	"archive": []pkg{
		pkg{path: "archive", dir: "/go/src/archive"},
	},
	"des": []pkg{
		pkg{path: "crypto/des", dir: "/go/src/crypto/des"},
	},
	"rsa": []pkg{
		pkg{path: "crypto/rsa", dir: "/go/src/crypto/rsa"},
	},
	"asn1": []pkg{
		pkg{path: "encoding/asn1", dir: "/go/src/encoding/asn1"},
	},
	"profile": []pkg{
		pkg{path: "cmd/pprof/internal/profile", dir: "/go/src/cmd/pprof/internal/profile"},
	},
	"format": []pkg{
		pkg{path: "go/format", dir: "/go/src/go/format"},
	},
	"http": []pkg{
		pkg{path: "net/http", dir: "/go/src/net/http"},
	},
	"tar": []pkg{
		pkg{path: "archive/tar", dir: "/go/src/archive/tar"},
	},
	"addr2line": []pkg{
		pkg{path: "cmd/addr2line", dir: "/go/src/cmd/addr2line"},
	},
	"base64": []pkg{
		pkg{path: "encoding/base64", dir: "/go/src/encoding/base64"},
	},
	"json": []pkg{
		pkg{path: "encoding/json", dir: "/go/src/encoding/json"},
	},
	"build": []pkg{
		pkg{path: "go/build", dir: "/go/src/go/build"},
	},
	"adler32": []pkg{
		pkg{path: "hash/adler32", dir: "/go/src/hash/adler32"},
	},
	"ioutil": []pkg{
		pkg{path: "io/ioutil", dir: "/go/src/io/ioutil"},
	},
	"rc4": []pkg{
		pkg{path: "crypto/rc4", dir: "/go/src/crypto/rc4"},
	},
	"draw": []pkg{
		pkg{path: "image/draw", dir: "/go/src/image/draw"},
	},
	"user": []pkg{
		pkg{path: "os/user", dir: "/go/src/os/user"},
	},
	"runtime": []pkg{
		pkg{path: "runtime", dir: "/go/src/runtime"},
	},
	"utf8": []pkg{
		pkg{path: "unicode/utf8", dir: "/go/src/unicode/utf8"},
	},
	"gc": []pkg{
		pkg{path: "cmd/gc", dir: "/go/src/cmd/gc"},
	},
	"gob": []pkg{
		pkg{path: "encoding/gob", dir: "/go/src/encoding/gob"},
	},
	"lib9": []pkg{
		pkg{path: "lib9", dir: "/go/src/lib9"},
	},
	"tabwriter": []pkg{
		pkg{path: "text/tabwriter", dir: "/go/src/text/tabwriter"},
	},
	"dist": []pkg{
		pkg{path: "cmd/dist", dir: "/go/src/cmd/dist"},
	},
	"container": []pkg{
		pkg{path: "container", dir: "/go/src/container"},
	},
	"crypto": []pkg{
		pkg{path: "crypto", dir: "/go/src/crypto"},
	},
	"aes": []pkg{
		pkg{path: "crypto/aes", dir: "/go/src/crypto/aes"},
	},
	"elliptic": []pkg{
		pkg{path: "crypto/elliptic", dir: "/go/src/crypto/elliptic"},
	},
	"net": []pkg{
		pkg{path: "net", dir: "/go/src/net"},
	},
	"url": []pkg{
		pkg{path: "net/url", dir: "/go/src/net/url"},
	},
	"compress": []pkg{
		pkg{path: "compress", dir: "/go/src/compress"},
	},
	"base32": []pkg{
		pkg{path: "encoding/base32", dir: "/go/src/encoding/base32"},
	},
	"palette": []pkg{
		pkg{path: "image/color/palette", dir: "/go/src/image/color/palette"},
	},
	"jpeg": []pkg{
		pkg{path: "image/jpeg", dir: "/go/src/image/jpeg"},
	},
	"utf": []pkg{
		pkg{path: "lib9/utf", dir: "/go/src/lib9/utf"},
	},
	"objfile": []pkg{
		pkg{path: "cmd/internal/objfile", dir: "/go/src/cmd/internal/objfile"},
	},
	"symbolizer": []pkg{
		pkg{path: "cmd/pprof/internal/symbolizer", dir: "/go/src/cmd/pprof/internal/symbolizer"},
	},
	"debug": []pkg{
		pkg{path: "debug", dir: "/go/src/debug"},
		pkg{path: "runtime/debug", dir: "/go/src/runtime/debug"},
	},
	"encoding": []pkg{
		pkg{path: "encoding", dir: "/go/src/encoding"},
	},
	"syslog": []pkg{
		pkg{path: "log/syslog", dir: "/go/src/log/syslog"},
	},
	"math": []pkg{
		pkg{path: "math", dir: "/go/src/math"},
	},
	"os": []pkg{
		pkg{path: "os", dir: "/go/src/os"},
	},
	"pem": []pkg{
		pkg{path: "encoding/pem", dir: "/go/src/encoding/pem"},
	},
	"printer": []pkg{
		pkg{path: "go/printer", dir: "/go/src/go/printer"},
	},
	"html": []pkg{
		pkg{path: "html", dir: "/go/src/html"},
	},
	"png": []pkg{
		pkg{path: "image/png", dir: "/go/src/image/png"},
	},
	"strconv": []pkg{
		pkg{path: "strconv", dir: "/go/src/strconv"},
	},
	"ring": []pkg{
		pkg{path: "container/ring", dir: "/go/src/container/ring"},
	},
	"errors": []pkg{
		pkg{path: "errors", dir: "/go/src/errors"},
	},
	"big": []pkg{
		pkg{path: "math/big", dir: "/go/src/math/big"},
	},
	"reflect": []pkg{
		pkg{path: "reflect", dir: "/go/src/reflect"},
	},
	"fetch": []pkg{
		pkg{path: "cmd/pprof/internal/fetch", dir: "/go/src/cmd/pprof/internal/fetch"},
	},
	"rand": []pkg{
		pkg{path: "crypto/rand", dir: "/go/src/crypto/rand"},
		pkg{path: "math/rand", dir: "/go/src/math/rand"},
	},
	"dwarf": []pkg{
		pkg{path: "debug/dwarf", dir: "/go/src/debug/dwarf"},
	},
	"expvar": []pkg{
		pkg{path: "expvar", dir: "/go/src/expvar"},
	},
	"cookiejar": []pkg{
		pkg{path: "net/http/cookiejar", dir: "/go/src/net/http/cookiejar"},
	},
	"builtin": []pkg{
		pkg{path: "builtin", dir: "/go/src/builtin"},
	},
	"internal": []pkg{
		pkg{path: "cmd/internal", dir: "/go/src/cmd/internal"},
		pkg{path: "cmd/pprof/internal", dir: "/go/src/cmd/pprof/internal"},
		pkg{path: "internal", dir: "/go/src/internal"},
		pkg{path: "net/http/internal", dir: "/go/src/net/http/internal"},
	},
	"gzip": []pkg{
		pkg{path: "compress/gzip", dir: "/go/src/compress/gzip"},
	},
	"ast": []pkg{
		pkg{path: "go/ast", dir: "/go/src/go/ast"},
	},
	"liblink": []pkg{
		pkg{path: "liblink", dir: "/go/src/liblink"},
	},
	"httputil": []pkg{
		pkg{path: "net/http/httputil", dir: "/go/src/net/http/httputil"},
	},
	"testing": []pkg{
		pkg{path: "testing", dir: "/go/src/testing"},
	},
	"commands": []pkg{
		pkg{path: "cmd/pprof/internal/commands", dir: "/go/src/cmd/pprof/internal/commands"},
	},
	"pack": []pkg{
		pkg{path: "cmd/pack", dir: "/go/src/cmd/pack"},
	},
	"cipher": []pkg{
		pkg{path: "crypto/cipher", dir: "/go/src/crypto/cipher"},
	},
	"sha512": []pkg{
		pkg{path: "crypto/sha512", dir: "/go/src/crypto/sha512"},
	},
	"pe": []pkg{
		pkg{path: "debug/pe", dir: "/go/src/debug/pe"},
	},
	"suffixarray": []pkg{
		pkg{path: "index/suffixarray", dir: "/go/src/index/suffixarray"},
	},
	"exec": []pkg{
		pkg{path: "os/exec", dir: "/go/src/os/exec"},
	},
	"time": []pkg{
		pkg{path: "time", dir: "/go/src/time"},
	},
	"x86": []pkg{
		pkg{path: "cmd/internal/rsc.io/x86", dir: "/go/src/cmd/internal/rsc.io/x86"},
	},
	"hex": []pkg{
		pkg{path: "encoding/hex", dir: "/go/src/encoding/hex"},
	},
	"crc32": []pkg{
		pkg{path: "hash/crc32", dir: "/go/src/hash/crc32"},
	},
	"image": []pkg{
		pkg{path: "image", dir: "/go/src/image"},
	},
	"iotest": []pkg{
		pkg{path: "testing/iotest", dir: "/go/src/testing/iotest"},
	},
	"arm": []pkg{
		pkg{path: "cmd/internal/rsc.io/arm", dir: "/go/src/cmd/internal/rsc.io/arm"},
	},
	"tempfile": []pkg{
		pkg{path: "cmd/pprof/internal/tempfile", dir: "/go/src/cmd/pprof/internal/tempfile"},
	},
	"list": []pkg{
		pkg{path: "container/list", dir: "/go/src/container/list"},
	},
	"subtle": []pkg{
		pkg{path: "crypto/subtle", dir: "/go/src/crypto/subtle"},
	},
	"template": []pkg{
		pkg{path: "html/template", dir: "/go/src/html/template"},
		pkg{path: "text/template", dir: "/go/src/text/template"},
	},
	"rpc": []pkg{
		pkg{path: "net/rpc", dir: "/go/src/net/rpc"},
	},
	"bufio": []pkg{
		pkg{path: "bufio", dir: "/go/src/bufio"},
	},
	"driver": []pkg{
		pkg{path: "cmd/pprof/internal/driver", dir: "/go/src/cmd/pprof/internal/driver"},
		pkg{path: "database/sql/driver", dir: "/go/src/database/sql/driver"},
	},
	"sha256": []pkg{
		pkg{path: "crypto/sha256", dir: "/go/src/crypto/sha256"},
	},
	"database": []pkg{
		pkg{path: "database", dir: "/go/src/database"},
	},
	"binary": []pkg{
		pkg{path: "encoding/binary", dir: "/go/src/encoding/binary"},
	},
	"flag": []pkg{
		pkg{path: "flag", dir: "/go/src/flag"},
	},
	"cgi": []pkg{
		pkg{path: "net/http/cgi", dir: "/go/src/net/http/cgi"},
	},
	"ld": []pkg{
		pkg{path: "cmd/ld", dir: "/go/src/cmd/ld"},
	},
	"md5": []pkg{
		pkg{path: "crypto/md5", dir: "/go/src/crypto/md5"},
	},
	"fcgi": []pkg{
		pkg{path: "net/http/fcgi", dir: "/go/src/net/http/fcgi"},
	},
	"regexp": []pkg{
		pkg{path: "regexp", dir: "/go/src/regexp"},
	},
	"go": []pkg{
		pkg{path: "cmd/go", dir: "/go/src/cmd/go"},
		pkg{path: "go", dir: "/go/src/go"},
	},
	"lzw": []pkg{
		pkg{path: "compress/lzw", dir: "/go/src/compress/lzw"},
	},
	"zlib": []pkg{
		pkg{path: "compress/zlib", dir: "/go/src/compress/zlib"},
	},
	"sha1": []pkg{
		pkg{path: "crypto/sha1", dir: "/go/src/crypto/sha1"},
	},
	"pkix": []pkg{
		pkg{path: "crypto/x509/pkix", dir: "/go/src/crypto/x509/pkix"},
	},
	"fnv": []pkg{
		pkg{path: "hash/fnv", dir: "/go/src/hash/fnv"},
	},
	"httptest": []pkg{
		pkg{path: "net/http/httptest", dir: "/go/src/net/http/httptest"},
	},
	"syntax": []pkg{
		pkg{path: "regexp/syntax", dir: "/go/src/regexp/syntax"},
	},
	"doc": []pkg{
		pkg{path: "go/doc", dir: "/go/src/go/doc"},
	},
	"token": []pkg{
		pkg{path: "go/token", dir: "/go/src/go/token"},
	},
	"crc64": []pkg{
		pkg{path: "hash/crc64", dir: "/go/src/hash/crc64"},
	},
	"multipart": []pkg{
		pkg{path: "mime/multipart", dir: "/go/src/mime/multipart"},
	},
	"path": []pkg{
		pkg{path: "path", dir: "/go/src/path"},
	},
	"atomic": []pkg{
		pkg{path: "sync/atomic", dir: "/go/src/sync/atomic"},
	},
	"text": []pkg{
		pkg{path: "text", dir: "/go/src/text"},
	},
	"gofmt": []pkg{
		pkg{path: "cmd/gofmt", dir: "/go/src/cmd/gofmt"},
	},
	"flate": []pkg{
		pkg{path: "compress/flate", dir: "/go/src/compress/flate"},
	},
	"elf": []pkg{
		pkg{path: "debug/elf", dir: "/go/src/debug/elf"},
	},
	"plan9obj": []pkg{
		pkg{path: "debug/plan9obj", dir: "/go/src/debug/plan9obj"},
	},
	"log": []pkg{
		pkg{path: "log", dir: "/go/src/log"},
	},
	"quick": []pkg{
		pkg{path: "testing/quick", dir: "/go/src/testing/quick"},
	},
	"utf16": []pkg{
		pkg{path: "unicode/utf16", dir: "/go/src/unicode/utf16"},
	},
	"cgo": []pkg{
		pkg{path: "cmd/cgo", dir: "/go/src/cmd/cgo"},
		pkg{path: "runtime/cgo", dir: "/go/src/runtime/cgo"},
	},
	"fmt": []pkg{
		pkg{path: "fmt", dir: "/go/src/fmt"},
		pkg{path: "lib9/fmt", dir: "/go/src/lib9/fmt"},
	},
	"bzip2": []pkg{
		pkg{path: "compress/bzip2", dir: "/go/src/compress/bzip2"},
	},
	"ascii85": []pkg{
		pkg{path: "encoding/ascii85", dir: "/go/src/encoding/ascii85"},
	},
	"strings": []pkg{
		pkg{path: "strings", dir: "/go/src/strings"},
	},
	"ecdsa": []pkg{
		pkg{path: "crypto/ecdsa", dir: "/go/src/crypto/ecdsa"},
	},
	"tls": []pkg{
		pkg{path: "crypto/tls", dir: "/go/src/crypto/tls"},
	},
	"smtp": []pkg{
		pkg{path: "net/smtp", dir: "/go/src/net/smtp"},
	},
	"unicode": []pkg{
		pkg{path: "unicode", dir: "/go/src/unicode"},
	},
}
