// AUTO-GENERATED BY generate_std_pkgs.go

package packages

var stdpkgs = map[string][]stdpkg{
	"nm": []stdpkg{
		stdpkg{path: "cmd/nm", dir: "/go/src/cmd/nm"},
	},
	"sha1": []stdpkg{
		stdpkg{path: "crypto/sha1", dir: "/go/src/crypto/sha1"},
	},
	"csv": []stdpkg{
		stdpkg{path: "encoding/csv", dir: "/go/src/encoding/csv"},
	},
	"flag": []stdpkg{
		stdpkg{path: "flag", dir: "/go/src/flag"},
	},
	"draw": []stdpkg{
		stdpkg{path: "image/draw", dir: "/go/src/image/draw"},
	},
	"textproto": []stdpkg{
		stdpkg{path: "net/textproto", dir: "/go/src/net/textproto"},
	},
	"urlfetch": []stdpkg{
		stdpkg{path: "appengine/urlfetch", dir: ""},
	},
	"cover": []stdpkg{
		stdpkg{path: "cmd/cover", dir: "/go/src/cmd/cover"},
	},
	"yacc": []stdpkg{
		stdpkg{path: "cmd/yacc", dir: "/go/src/cmd/yacc"},
	},
	"cipher": []stdpkg{
		stdpkg{path: "crypto/cipher", dir: "/go/src/crypto/cipher"},
	},
	"encoding": []stdpkg{
		stdpkg{path: "encoding", dir: "/go/src/encoding"},
	},
	"strconv": []stdpkg{
		stdpkg{path: "strconv", dir: "/go/src/strconv"},
	},
	"profile": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/profile", dir: "/go/src/cmd/pprof/internal/profile"},
	},
	"ring": []stdpkg{
		stdpkg{path: "container/ring", dir: "/go/src/container/ring"},
	},
	"httputil": []stdpkg{
		stdpkg{path: "net/http/httputil", dir: "/go/src/net/http/httputil"},
	},
	"regexp": []stdpkg{
		stdpkg{path: "regexp", dir: "/go/src/regexp"},
	},
	"http": []stdpkg{
		stdpkg{path: "net/http", dir: "/go/src/net/http"},
	},
	"x86": []stdpkg{
		stdpkg{path: "cmd/compile/internal/x86", dir: "/go/src/cmd/compile/internal/x86"},
		stdpkg{path: "cmd/internal/obj/x86", dir: "/go/src/cmd/internal/obj/x86"},
		stdpkg{path: "cmd/internal/rsc.io/x86", dir: "/go/src/cmd/internal/rsc.io/x86"},
		stdpkg{path: "cmd/link/internal/x86", dir: "/go/src/cmd/link/internal/x86"},
	},
	"goobj": []stdpkg{
		stdpkg{path: "cmd/internal/goobj", dir: "/go/src/cmd/internal/goobj"},
	},
	"lzw": []stdpkg{
		stdpkg{path: "compress/lzw", dir: "/go/src/compress/lzw"},
	},
	"importer": []stdpkg{
		stdpkg{path: "go/importer", dir: "/go/src/go/importer"},
	},
	"gccgoimporter": []stdpkg{
		stdpkg{path: "go/internal/gccgoimporter", dir: "/go/src/go/internal/gccgoimporter"},
	},
	"suffixarray": []stdpkg{
		stdpkg{path: "index/suffixarray", dir: "/go/src/index/suffixarray"},
	},
	"net": []stdpkg{
		stdpkg{path: "net", dir: "/go/src/net"},
	},
	"syntax": []stdpkg{
		stdpkg{path: "regexp/syntax", dir: "/go/src/regexp/syntax"},
	},
	"path": []stdpkg{
		stdpkg{path: "path", dir: "/go/src/path"},
	},
	"fix": []stdpkg{
		stdpkg{path: "cmd/fix", dir: "/go/src/cmd/fix"},
	},
	"vet": []stdpkg{
		stdpkg{path: "cmd/vet", dir: "/go/src/cmd/vet"},
	},
	"base64": []stdpkg{
		stdpkg{path: "encoding/base64", dir: "/go/src/encoding/base64"},
	},
	"hash": []stdpkg{
		stdpkg{path: "hash", dir: "/go/src/hash"},
	},
	"html": []stdpkg{
		stdpkg{path: "html", dir: "/go/src/html"},
	},
	"windows": []stdpkg{
		stdpkg{path: "internal/syscall/windows", dir: "/go/src/internal/syscall/windows"},
	},
	"testenv": []stdpkg{
		stdpkg{path: "internal/testenv", dir: "/go/src/internal/testenv"},
	},
	"quick": []stdpkg{
		stdpkg{path: "testing/quick", dir: "/go/src/testing/quick"},
	},
	"format": []stdpkg{
		stdpkg{path: "go/format", dir: "/go/src/go/format"},
		stdpkg{path: "internal/format", dir: "/go/src/internal/format"},
	},
	"parser": []stdpkg{
		stdpkg{path: "go/parser", dir: "/go/src/go/parser"},
	},
	"log": []stdpkg{
		stdpkg{path: "log", dir: "/go/src/log"},
	},
	"filepath": []stdpkg{
		stdpkg{path: "path/filepath", dir: "/go/src/path/filepath"},
	},
	"iotest": []stdpkg{
		stdpkg{path: "testing/iotest", dir: "/go/src/testing/iotest"},
	},
	"fcgi": []stdpkg{
		stdpkg{path: "net/http/fcgi", dir: "/go/src/net/http/fcgi"},
	},
	"user": []stdpkg{
		stdpkg{path: "os/user", dir: "/go/src/os/user"},
	},
	"utf8": []stdpkg{
		stdpkg{path: "unicode/utf8", dir: "/go/src/unicode/utf8"},
	},
	"symbolizer": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/symbolizer", dir: "/go/src/cmd/pprof/internal/symbolizer"},
	},
	"dwarf": []stdpkg{
		stdpkg{path: "debug/dwarf", dir: "/go/src/debug/dwarf"},
	},
	"token": []stdpkg{
		stdpkg{path: "go/token", dir: "/go/src/go/token"},
	},
	"adler32": []stdpkg{
		stdpkg{path: "hash/adler32", dir: "/go/src/hash/adler32"},
	},
	"crc32": []stdpkg{
		stdpkg{path: "hash/crc32", dir: "/go/src/hash/crc32"},
	},
	"atomic": []stdpkg{
		stdpkg{path: "sync/atomic", dir: "/go/src/sync/atomic"},
	},
	"jsonrpc": []stdpkg{
		stdpkg{path: "net/rpc/jsonrpc", dir: "/go/src/net/rpc/jsonrpc"},
	},
	"arch": []stdpkg{
		stdpkg{path: "cmd/asm/internal/arch", dir: "/go/src/cmd/asm/internal/arch"},
	},
	"obj": []stdpkg{
		stdpkg{path: "cmd/internal/obj", dir: "/go/src/cmd/internal/obj"},
	},
	"gzip": []stdpkg{
		stdpkg{path: "compress/gzip", dir: "/go/src/compress/gzip"},
	},
	"debug": []stdpkg{
		stdpkg{path: "debug", dir: "/go/src/debug"},
		stdpkg{path: "runtime/debug", dir: "/go/src/runtime/debug"},
	},
	"template": []stdpkg{
		stdpkg{path: "html/template", dir: "/go/src/html/template"},
		stdpkg{path: "text/template", dir: "/go/src/text/template"},
	},
	"index": []stdpkg{
		stdpkg{path: "index", dir: "/go/src/index"},
	},
	"cmplx": []stdpkg{
		stdpkg{path: "math/cmplx", dir: "/go/src/math/cmplx"},
	},
	"testing": []stdpkg{
		stdpkg{path: "testing", dir: "/go/src/testing"},
	},
	"tabwriter": []stdpkg{
		stdpkg{path: "text/tabwriter", dir: "/go/src/text/tabwriter"},
	},
	"time": []stdpkg{
		stdpkg{path: "time", dir: "/go/src/time"},
	},
	"bytes": []stdpkg{
		stdpkg{path: "bytes", dir: "/go/src/bytes"},
	},
	"cgo": []stdpkg{
		stdpkg{path: "cmd/cgo", dir: "/go/src/cmd/cgo"},
		stdpkg{path: "runtime/cgo", dir: "/go/src/runtime/cgo"},
	},
	"jpeg": []stdpkg{
		stdpkg{path: "image/jpeg", dir: "/go/src/image/jpeg"},
	},
	"unicode": []stdpkg{
		stdpkg{path: "unicode", dir: "/go/src/unicode"},
	},
	"cmd": []stdpkg{
		stdpkg{path: "cmd", dir: "/go/src/cmd"},
	},
	"rsc.io": []stdpkg{
		stdpkg{path: "cmd/internal/rsc.io", dir: "/go/src/cmd/internal/rsc.io"},
	},
	"types": []stdpkg{
		stdpkg{path: "go/types", dir: "/go/src/go/types"},
	},
	"imageutil": []stdpkg{
		stdpkg{path: "image/internal/imageutil", dir: "/go/src/image/internal/imageutil"},
	},
	"png": []stdpkg{
		stdpkg{path: "image/png", dir: "/go/src/image/png"},
	},
	"url": []stdpkg{
		stdpkg{path: "net/url", dir: "/go/src/net/url"},
	},
	"runtime": []stdpkg{
		stdpkg{path: "runtime", dir: "/go/src/runtime"},
	},
	"arm": []stdpkg{
		stdpkg{path: "cmd/compile/internal/arm", dir: "/go/src/cmd/compile/internal/arm"},
		stdpkg{path: "cmd/internal/obj/arm", dir: "/go/src/cmd/internal/obj/arm"},
		stdpkg{path: "cmd/internal/rsc.io/arm", dir: "/go/src/cmd/internal/rsc.io/arm"},
		stdpkg{path: "cmd/link/internal/arm", dir: "/go/src/cmd/link/internal/arm"},
	},
	"ld": []stdpkg{
		stdpkg{path: "cmd/link/internal/ld", dir: "/go/src/cmd/link/internal/ld"},
	},
	"quotedprintable": []stdpkg{
		stdpkg{path: "mime/quotedprintable", dir: "/go/src/mime/quotedprintable"},
	},
	"mail": []stdpkg{
		stdpkg{path: "net/mail", dir: "/go/src/net/mail"},
	},
	"text": []stdpkg{
		stdpkg{path: "text", dir: "/go/src/text"},
	},
	"archive": []stdpkg{
		stdpkg{path: "archive", dir: "/go/src/archive"},
	},
	"arm64": []stdpkg{
		stdpkg{path: "cmd/compile/internal/arm64", dir: "/go/src/cmd/compile/internal/arm64"},
		stdpkg{path: "cmd/internal/obj/arm64", dir: "/go/src/cmd/internal/obj/arm64"},
		stdpkg{path: "cmd/link/internal/arm64", dir: "/go/src/cmd/link/internal/arm64"},
	},
	"big": []stdpkg{
		stdpkg{path: "cmd/compile/internal/big", dir: "/go/src/cmd/compile/internal/big"},
		stdpkg{path: "math/big", dir: "/go/src/math/big"},
	},
	"gc": []stdpkg{
		stdpkg{path: "cmd/compile/internal/gc", dir: "/go/src/cmd/compile/internal/gc"},
	},
	"driver": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/driver", dir: "/go/src/cmd/pprof/internal/driver"},
		stdpkg{path: "database/sql/driver", dir: "/go/src/database/sql/driver"},
	},
	"gob": []stdpkg{
		stdpkg{path: "encoding/gob", dir: "/go/src/encoding/gob"},
	},
	"multipart": []stdpkg{
		stdpkg{path: "mime/multipart", dir: "/go/src/mime/multipart"},
	},
	"amd64": []stdpkg{
		stdpkg{path: "cmd/compile/internal/amd64", dir: "/go/src/cmd/compile/internal/amd64"},
		stdpkg{path: "cmd/link/internal/amd64", dir: "/go/src/cmd/link/internal/amd64"},
	},
	"xml": []stdpkg{
		stdpkg{path: "encoding/xml", dir: "/go/src/encoding/xml"},
	},
	"exec": []stdpkg{
		stdpkg{path: "os/exec", dir: "/go/src/os/exec"},
	},
	"api": []stdpkg{
		stdpkg{path: "cmd/api", dir: "/go/src/cmd/api"},
	},
	"commands": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/commands", dir: "/go/src/cmd/pprof/internal/commands"},
	},
	"bzip2": []stdpkg{
		stdpkg{path: "compress/bzip2", dir: "/go/src/compress/bzip2"},
	},
	"crypto": []stdpkg{
		stdpkg{path: "crypto", dir: "/go/src/crypto"},
	},
	"asn1": []stdpkg{
		stdpkg{path: "encoding/asn1", dir: "/go/src/encoding/asn1"},
	},
	"syslog": []stdpkg{
		stdpkg{path: "log/syslog", dir: "/go/src/log/syslog"},
	},
	"bufio": []stdpkg{
		stdpkg{path: "bufio", dir: "/go/src/bufio"},
	},
	"builtin": []stdpkg{
		stdpkg{path: "builtin", dir: "/go/src/builtin"},
		stdpkg{path: "cmd/compile/internal/gc/builtin", dir: "/go/src/cmd/compile/internal/gc/builtin"},
	},
	"go": []stdpkg{
		stdpkg{path: "cmd/go", dir: "/go/src/cmd/go"},
		stdpkg{path: "go", dir: "/go/src/go"},
	},
	"heap": []stdpkg{
		stdpkg{path: "container/heap", dir: "/go/src/container/heap"},
	},
	"rsa": []stdpkg{
		stdpkg{path: "crypto/rsa", dir: "/go/src/crypto/rsa"},
	},
	"elf": []stdpkg{
		stdpkg{path: "debug/elf", dir: "/go/src/debug/elf"},
	},
	"strings": []stdpkg{
		stdpkg{path: "strings", dir: "/go/src/strings"},
	},
	"compile": []stdpkg{
		stdpkg{path: "cmd/compile", dir: "/go/src/cmd/compile"},
	},
	"x86asm": []stdpkg{
		stdpkg{path: "cmd/internal/rsc.io/x86/x86asm", dir: "/go/src/cmd/internal/rsc.io/x86/x86asm"},
	},
	"objdump": []stdpkg{
		stdpkg{path: "cmd/objdump", dir: "/go/src/cmd/objdump"},
	},
	"ecdsa": []stdpkg{
		stdpkg{path: "crypto/ecdsa", dir: "/go/src/crypto/ecdsa"},
	},
	"gif": []stdpkg{
		stdpkg{path: "image/gif", dir: "/go/src/image/gif"},
	},
	"unix": []stdpkg{
		stdpkg{path: "internal/syscall/unix", dir: "/go/src/internal/syscall/unix"},
	},
	"io": []stdpkg{
		stdpkg{path: "io", dir: "/go/src/io"},
	},
	"socktest": []stdpkg{
		stdpkg{path: "net/internal/socktest", dir: "/go/src/net/internal/socktest"},
	},
	"asm": []stdpkg{
		stdpkg{path: "cmd/asm", dir: "/go/src/cmd/asm"},
		stdpkg{path: "cmd/asm/internal/asm", dir: "/go/src/cmd/asm/internal/asm"},
	},
	"flags": []stdpkg{
		stdpkg{path: "cmd/asm/internal/flags", dir: "/go/src/cmd/asm/internal/flags"},
	},
	"doc": []stdpkg{
		stdpkg{path: "cmd/doc", dir: "/go/src/cmd/doc"},
		stdpkg{path: "go/doc", dir: "/go/src/go/doc"},
	},
	"svg": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/svg", dir: "/go/src/cmd/pprof/internal/svg"},
	},
	"hmac": []stdpkg{
		stdpkg{path: "crypto/hmac", dir: "/go/src/crypto/hmac"},
	},
	"md5": []stdpkg{
		stdpkg{path: "crypto/md5", dir: "/go/src/crypto/md5"},
	},
	"palette": []stdpkg{
		stdpkg{path: "image/color/palette", dir: "/go/src/image/color/palette"},
	},
	"utf16": []stdpkg{
		stdpkg{path: "unicode/utf16", dir: "/go/src/unicode/utf16"},
	},
	"unsafe": []stdpkg{
		stdpkg{path: "unsafe", dir: "/go/src/unsafe"},
	},
	"zip": []stdpkg{
		stdpkg{path: "archive/zip", dir: "/go/src/archive/zip"},
	},
	"internal": []stdpkg{
		stdpkg{path: "cmd/asm/internal", dir: "/go/src/cmd/asm/internal"},
		stdpkg{path: "cmd/compile/internal", dir: "/go/src/cmd/compile/internal"},
		stdpkg{path: "cmd/internal", dir: "/go/src/cmd/internal"},
		stdpkg{path: "cmd/link/internal", dir: "/go/src/cmd/link/internal"},
		stdpkg{path: "cmd/pprof/internal", dir: "/go/src/cmd/pprof/internal"},
		stdpkg{path: "go/internal", dir: "/go/src/go/internal"},
		stdpkg{path: "image/internal", dir: "/go/src/image/internal"},
		stdpkg{path: "internal", dir: "/go/src/internal"},
		stdpkg{path: "net/http/internal", dir: "/go/src/net/http/internal"},
		stdpkg{path: "net/internal", dir: "/go/src/net/internal"},
	},
	"symbolz": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/symbolz", dir: "/go/src/cmd/pprof/internal/symbolz"},
	},
	"des": []stdpkg{
		stdpkg{path: "crypto/des", dir: "/go/src/crypto/des"},
	},
	"macho": []stdpkg{
		stdpkg{path: "debug/macho", dir: "/go/src/debug/macho"},
	},
	"crc64": []stdpkg{
		stdpkg{path: "hash/crc64", dir: "/go/src/hash/crc64"},
	},
	"syscall": []stdpkg{
		stdpkg{path: "internal/syscall", dir: "/go/src/internal/syscall"},
		stdpkg{path: "syscall", dir: "/go/src/syscall"},
	},
	"report": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/report", dir: "/go/src/cmd/pprof/internal/report"},
	},
	"cgi": []stdpkg{
		stdpkg{path: "net/http/cgi", dir: "/go/src/net/http/cgi"},
	},
	"sort": []stdpkg{
		stdpkg{path: "sort", dir: "/go/src/sort"},
	},
	"pack": []stdpkg{
		stdpkg{path: "cmd/pack", dir: "/go/src/cmd/pack"},
	},
	"plugin": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/plugin", dir: "/go/src/cmd/pprof/internal/plugin"},
	},
	"sha512": []stdpkg{
		stdpkg{path: "crypto/sha512", dir: "/go/src/crypto/sha512"},
	},
	"pe": []stdpkg{
		stdpkg{path: "debug/pe", dir: "/go/src/debug/pe"},
	},
	"ast": []stdpkg{
		stdpkg{path: "go/ast", dir: "/go/src/go/ast"},
	},
	"math": []stdpkg{
		stdpkg{path: "math", dir: "/go/src/math"},
	},
	"smtp": []stdpkg{
		stdpkg{path: "net/smtp", dir: "/go/src/net/smtp"},
	},
	"compress": []stdpkg{
		stdpkg{path: "compress", dir: "/go/src/compress"},
	},
	"list": []stdpkg{
		stdpkg{path: "container/list", dir: "/go/src/container/list"},
	},
	"ascii85": []stdpkg{
		stdpkg{path: "encoding/ascii85", dir: "/go/src/encoding/ascii85"},
	},
	"httptest": []stdpkg{
		stdpkg{path: "net/http/httptest", dir: "/go/src/net/http/httptest"},
	},
	"objfile": []stdpkg{
		stdpkg{path: "cmd/internal/objfile", dir: "/go/src/cmd/internal/objfile"},
	},
	"x509": []stdpkg{
		stdpkg{path: "crypto/x509", dir: "/go/src/crypto/x509"},
	},
	"database": []stdpkg{
		stdpkg{path: "database", dir: "/go/src/database"},
	},
	"plan9obj": []stdpkg{
		stdpkg{path: "debug/plan9obj", dir: "/go/src/debug/plan9obj"},
	},
	"cookiejar": []stdpkg{
		stdpkg{path: "net/http/cookiejar", dir: "/go/src/net/http/cookiejar"},
	},
	"reflect": []stdpkg{
		stdpkg{path: "reflect", dir: "/go/src/reflect"},
	},
	"race": []stdpkg{
		stdpkg{path: "runtime/race", dir: "/go/src/runtime/race"},
	},
	"dist": []stdpkg{
		stdpkg{path: "cmd/dist", dir: "/go/src/cmd/dist"},
	},
	"rand": []stdpkg{
		stdpkg{path: "crypto/rand", dir: "/go/src/crypto/rand"},
		stdpkg{path: "math/rand", dir: "/go/src/math/rand"},
	},
	"fnv": []stdpkg{
		stdpkg{path: "hash/fnv", dir: "/go/src/hash/fnv"},
	},
	"image": []stdpkg{
		stdpkg{path: "image", dir: "/go/src/image"},
	},
	"singleflight": []stdpkg{
		stdpkg{path: "internal/singleflight", dir: "/go/src/internal/singleflight"},
	},
	"os": []stdpkg{
		stdpkg{path: "os", dir: "/go/src/os"},
	},
	"tar": []stdpkg{
		stdpkg{path: "archive/tar", dir: "/go/src/archive/tar"},
	},
	"ppc64": []stdpkg{
		stdpkg{path: "cmd/compile/internal/ppc64", dir: "/go/src/cmd/compile/internal/ppc64"},
		stdpkg{path: "cmd/internal/obj/ppc64", dir: "/go/src/cmd/internal/obj/ppc64"},
		stdpkg{path: "cmd/link/internal/ppc64", dir: "/go/src/cmd/link/internal/ppc64"},
	},
	"sha256": []stdpkg{
		stdpkg{path: "crypto/sha256", dir: "/go/src/crypto/sha256"},
	},
	"sql": []stdpkg{
		stdpkg{path: "database/sql", dir: "/go/src/database/sql"},
	},
	"base32": []stdpkg{
		stdpkg{path: "encoding/base32", dir: "/go/src/encoding/base32"},
	},
	"registry": []stdpkg{
		stdpkg{path: "internal/syscall/windows/registry", dir: "/go/src/internal/syscall/windows/registry"},
	},
	"rpc": []stdpkg{
		stdpkg{path: "net/rpc", dir: "/go/src/net/rpc"},
	},
	"armasm": []stdpkg{
		stdpkg{path: "cmd/internal/rsc.io/arm/armasm", dir: "/go/src/cmd/internal/rsc.io/arm/armasm"},
	},
	"pprof": []stdpkg{
		stdpkg{path: "cmd/pprof", dir: "/go/src/cmd/pprof"},
		stdpkg{path: "net/http/pprof", dir: "/go/src/net/http/pprof"},
		stdpkg{path: "runtime/pprof", dir: "/go/src/runtime/pprof"},
	},
	"whitelist": []stdpkg{
		stdpkg{path: "cmd/vet/whitelist", dir: "/go/src/cmd/vet/whitelist"},
	},
	"rc4": []stdpkg{
		stdpkg{path: "crypto/rc4", dir: "/go/src/crypto/rc4"},
	},
	"hex": []stdpkg{
		stdpkg{path: "encoding/hex", dir: "/go/src/encoding/hex"},
	},
	"printer": []stdpkg{
		stdpkg{path: "go/printer", dir: "/go/src/go/printer"},
	},
	"ioutil": []stdpkg{
		stdpkg{path: "io/ioutil", dir: "/go/src/io/ioutil"},
	},
	"link": []stdpkg{
		stdpkg{path: "cmd/link", dir: "/go/src/cmd/link"},
	},
	"tempfile": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/tempfile", dir: "/go/src/cmd/pprof/internal/tempfile"},
	},
	"aes": []stdpkg{
		stdpkg{path: "crypto/aes", dir: "/go/src/crypto/aes"},
	},
	"elliptic": []stdpkg{
		stdpkg{path: "crypto/elliptic", dir: "/go/src/crypto/elliptic"},
	},
	"pkix": []stdpkg{
		stdpkg{path: "crypto/x509/pkix", dir: "/go/src/crypto/x509/pkix"},
	},
	"expvar": []stdpkg{
		stdpkg{path: "expvar", dir: "/go/src/expvar"},
	},
	"build": []stdpkg{
		stdpkg{path: "go/build", dir: "/go/src/go/build"},
	},
	"appengine": []stdpkg{
		stdpkg{path: "appengine", dir: ""},
	},
	"gofmt": []stdpkg{
		stdpkg{path: "cmd/gofmt", dir: "/go/src/cmd/gofmt"},
	},
	"subtle": []stdpkg{
		stdpkg{path: "crypto/subtle", dir: "/go/src/crypto/subtle"},
	},
	"mime": []stdpkg{
		stdpkg{path: "mime", dir: "/go/src/mime"},
	},
	"dsa": []stdpkg{
		stdpkg{path: "crypto/dsa", dir: "/go/src/crypto/dsa"},
	},
	"tls": []stdpkg{
		stdpkg{path: "crypto/tls", dir: "/go/src/crypto/tls"},
	},
	"color": []stdpkg{
		stdpkg{path: "image/color", dir: "/go/src/image/color"},
	},
	"signal": []stdpkg{
		stdpkg{path: "os/signal", dir: "/go/src/os/signal"},
	},
	"gcimporter": []stdpkg{
		stdpkg{path: "go/internal/gcimporter", dir: "/go/src/go/internal/gcimporter"},
	},
	"gcprog": []stdpkg{
		stdpkg{path: "cmd/internal/gcprog", dir: "/go/src/cmd/internal/gcprog"},
	},
	"fetch": []stdpkg{
		stdpkg{path: "cmd/pprof/internal/fetch", dir: "/go/src/cmd/pprof/internal/fetch"},
	},
	"trace": []stdpkg{
		stdpkg{path: "cmd/trace", dir: "/go/src/cmd/trace"},
		stdpkg{path: "internal/trace", dir: "/go/src/internal/trace"},
		stdpkg{path: "runtime/trace", dir: "/go/src/runtime/trace"},
	},
	"container": []stdpkg{
		stdpkg{path: "container", dir: "/go/src/container"},
	},
	"binary": []stdpkg{
		stdpkg{path: "encoding/binary", dir: "/go/src/encoding/binary"},
	},
	"pem": []stdpkg{
		stdpkg{path: "encoding/pem", dir: "/go/src/encoding/pem"},
	},
	"fmt": []stdpkg{
		stdpkg{path: "fmt", dir: "/go/src/fmt"},
	},
	"cloudsql": []stdpkg{
		stdpkg{path: "appengine/cloudsql", dir: ""},
	},
	"lex": []stdpkg{
		stdpkg{path: "cmd/asm/internal/lex", dir: "/go/src/cmd/asm/internal/lex"},
	},
	"flate": []stdpkg{
		stdpkg{path: "compress/flate", dir: "/go/src/compress/flate"},
	},
	"zlib": []stdpkg{
		stdpkg{path: "compress/zlib", dir: "/go/src/compress/zlib"},
	},
	"gosym": []stdpkg{
		stdpkg{path: "debug/gosym", dir: "/go/src/debug/gosym"},
	},
	"sync": []stdpkg{
		stdpkg{path: "sync", dir: "/go/src/sync"},
	},
	"parse": []stdpkg{
		stdpkg{path: "text/template/parse", dir: "/go/src/text/template/parse"},
	},
	"addr2line": []stdpkg{
		stdpkg{path: "cmd/addr2line", dir: "/go/src/cmd/addr2line"},
	},
	"json": []stdpkg{
		stdpkg{path: "encoding/json", dir: "/go/src/encoding/json"},
	},
	"errors": []stdpkg{
		stdpkg{path: "errors", dir: "/go/src/errors"},
	},
	"constant": []stdpkg{
		stdpkg{path: "go/constant", dir: "/go/src/go/constant"},
	},
	"scanner": []stdpkg{
		stdpkg{path: "go/scanner", dir: "/go/src/go/scanner"},
		stdpkg{path: "text/scanner", dir: "/go/src/text/scanner"},
	},
}

type stdpkg struct{ path, dir string }
